name: Run Ouroboros server
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_node_0]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v23.x
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          cache: npm
      
      - name: Install dependencies
        run: npm run setup

      - name: start API server
        run: |
          HEADLESS=true NODEID=0 nohup npm run serve


      - name: RUN API SERVER FOR 5H, 3min for test
        run: sleep 180

      - name: Run this Action again
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.RUN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger_node_1"}'

      - name: PAUSE TO TRANSFER DATA FROM NODE 0 TO NODE 1, 30min
        run: sleep 1800