name: Run Ouroboros server
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_recursive_workflow]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v23.x
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          cache: npm
      
      - name: Install dependencies
        run: npm ci

      - name: List files in 'out' directory
        run: |
          echo "$PWD"
          ls -R ./

      - name: start API server
        run: node ouroboros.mts

      - name: RUN API SERVER FOR 1H
        run: sleep 3600

    #   - name: Run this Action again
    #     run: |
    #       curl -X POST \
    #       -H "Accept: application/vnd.github+json" \
    #       -H "Authorization: Bearer ${{ secrets.RUN }}" \
    #       -H "X-GitHub-Api-Version: 2022-11-28" \
    #       https://api.github.com/repos/${{ github.repository }}/dispatches \
    #       -d '{"event_type":"trigger_recursive_workflow"}'